# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3eebe97ddd06b05485ac55f1b12fa732ea292f20616e22fd55eda28851b994970e78146d90ac30782fda942d691d8bcecc63140dac33dd2542b96be497117276
  paypal_client_id: <%ENV["PAYPAL_CLIENT_ID"]%>
  paypal_secret_id: <%ENV["PAYPAL_SECRET_ID"]%>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"]%>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"]%>

test:
  secret_key_base: 5ceded694e7b81397f6b776596583286be59c67fb4fec82deb8f1aa355279b5eee316e9784b18250c3145220df7ee56a1ca366846d7ae041b6d2b34326164955

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_client_id: <%ENV["PAYPAL_CLIENT_ID"]%>
  paypal_secret_id: <%ENV["PAYPAL_SECRET_ID"]%>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"]%>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"]%>